version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverse-proxy
    image: rodpassos/udagram-reverse-proxy
  backend_user:
    build:
      context: ./udagram-api-users
    image: rodpassos/udagram-api-users
  backend_feed:
    build:
      context: ./udagram-api-feed
    image: rodpassos/udagram-api-feed
  frontend:
    build:
      context: ./udagram-frontend
    image: rodpassos/udagram-frontend